#159987690 User should get verification email after signup
andela/thor-ah pull request #15
Opened 2018-09-01 16:01 UTC by emmaadesile

#### What does this PR do?
Implement feature to send a verification email to a user after successful signup

#### Description of Task to be completed?
- add two new endpoints to the routes
  ```
  GET /api/verify-email/id
   GET /api/confirmation/:token
  ```

#### How should this be manually tested?
- After cloning the app
- run `npm install`
- Install and setup Postgres
- on postman, make a post request to `/api/users` to signup
- now go to make a get request to `/api/verify-email/:id` where id is the id of the new user
- copy the *link* in the sent and use it to make a get request to `/confirmation/:token`
- you should get a message that the email has been confirmed

#### What are the relevant pivotal tracker stories?
(159987690)[https://www.pivotaltracker.com/story/show/159987690]

2018-09-01 19:53 UTC, aknwosu commented on server/controllers/emailVerificationController.js
> +        .catch(error => console.log(error))
console.log? Properly catch errors sending appropriate message and status

2018-09-01 20:04 UTC, aknwosu commented
@emmaadesile Sync with @CEOehis to fix Travis error, standardize your object notations. e.g. use { expect } or {expect} consistently with { expect } being the preferred

2018-09-02 13:44 UTC, emekafredy reviewed
Resolve issues with houndCI

2018-09-04 18:10 UTC, aknwosu requested changes

2018-09-04 18:10 UTC, aknwosu commented on server/controllers/emailVerificationController.js
> +            message: 'User does not exist in database'
message: 'User does not exist'

2018-09-04 18:10 UTC, aknwosu commented on server/controllers/emailVerificationController.js
> +        const url = `http://localhost:3000/api/users/confirmation/${emailToken}`;
have this in your env file

2018-09-04 18:10 UTC, aknwosu commented on server/controllers/emailVerificationController.js
> +          subject: 'Authors Haven Email Verification',
Authors' Haven Email Verification. apostrophe missing

2018-09-04 18:10 UTC, aknwosu commented on server/controllers/users.js
> +const { User } = db;
import { User } from '../models'

2018-09-04 18:10 UTC, aknwosu commented on server/controllers/users.js
> +              user,
check the response object from others and make this correspond

2018-09-04 18:10 UTC, aknwosu commented on server/controllers/users.js
> +              return res.status(200).json({ dataValues });
correct all your response objects and standardize them

2018-09-04 18:10 UTC, aknwosu commented on server/controllers/users.js
> +              return res.status(200).json({ dataValues });
really? anything as the response??

2018-09-04 18:10 UTC, aknwosu commented on server/controllers/emailVerificationController.js
> +      const url = `http://localhost:3000/api/users/confirmation/${emailToken}`;
if you hardcode the url here, what happens in production?

2018-09-04 18:12 UTC, aknwosu commented
I don't expect to still have to ask anyone to fix hound issues at this point

2018-09-05 12:03 UTC, closed without merging