#159987727 Add favourite articles function
andela/thor-ah pull request #46
Opened 2018-09-12 14:57 UTC by d-beloved

#### What does this PR do?
- Add ability for a user to be able to favorite certain articles
- List the articles favorited by a user
- deletes articles favorited by a user

#### How should this be manually tested?
Run 'npm install'
create a .env using the .env.sample template
Run 'npm run migrate'
Run 'npm run start:dev'
use postman to test:
```routes added```
post: /api/articles/:articlesId/favorite
delete: /api/articles/:articlesId/favorite
get: /api/user/articles/favorite

#### What are the relevant pivotal tracker stories?
 #159987727

2018-09-12 16:09 UTC, gonuoha requested changes
please change you error responses to conform to the format we have been using ... {
status: 'error',
errors: {message: '...'}
}

2018-09-12 16:37 UTC, emekafredy requested changes
Please make sure to update the swagger docs file with your endpoints. reach out to @lauragift21 on this if you need help.

2018-09-12 21:46 UTC, aknwosu requested changes

2018-09-12 21:46 UTC, aknwosu commented on server/routes/api/favoriteArticle.js
> +import auth from '../../middleware/auth';
import {authenticateUser} from '../../middleware/auth';

2018-09-12 21:46 UTC, aknwosu commented on server/routes/api/favoriteArticle.js
> +const { authenticateUser } = auth;
remove this

2018-09-12 21:46 UTC, aknwosu commented on server/routes/api/favoriteArticle.js
> +const { authenticateUser } = auth;
you can remove this after modifying line 2

2018-09-13 04:22 UTC, d-beloved commented on server/routes/api/favoriteArticle.js
> +import auth from '../../middleware/auth';
Thanks, I've effected this change

2018-09-13 07:45 UTC, emekafredy approved these changes
LGTM

2018-09-13 08:24 UTC, gonuoha approved these changes

2018-09-13 09:15 UTC, aknwosu approved these changes

2018-09-13 09:15 UTC, merged