#160555688 Super admin can update user roles
andela/thor-ah pull request #54
Opened 2018-09-18 09:15 UTC by CEOehis

#### What does this PR do?
implement the ability for a super admin to assign and revoke admin roles

#### Description of Task to be completed?
Only a super admin has access to this endpoint in the application. The super admin can make users into "admins" and can revoke such access.
- include relevant tests
- add methods to handle user role update
- update swagger doc

#### How should this be manually tested?
Run `npm run start:dev`
log in with a super-admin account
send a `POST` request to `/api/admin/:userId/roles` using the super-admin token in the `Authorization` header to make a user an admin.
send a `DELETE` request to `/api/admin/:userId/roles` using the super-admin token in the `Authorization` header to revoke the admin access

#### What are the relevant pivotal tracker stories?
[#160555688](https://www.pivotaltracker.com/story/show/160555688)

2018-09-18 16:38 UTC, emmaadesile requested changes

2018-09-18 16:38 UTC, emmaadesile commented on server/routes/api/admin.js
>  const adminRoutes = require('express').Router();
Good work declaring the adminRoutes on one line but you can make it more es6.
```
import { Router } from 'express'
const adminRoutes = Router();
```

2018-09-18 17:03 UTC, iamuchejude requested changes
Implement fix on line 46 of adminHandleRoles.js in controller folder.
I also think some of your comments are not really necessary like you have on line 2 of `server/migrations/20180916093338-user-add-super-admin-role.js`. 
Here is an article on the best practices for commenting your code to guide you: https://improvingsoftware.com/2011/06/27/5-best-practices-for-commenting-your-code/

2018-09-18 17:03 UTC, iamuchejude commented on server/controllers/adminHandleRoles.js
> +   * assign a user an admin role
Misleading comment. 
From what I see, the method is revoking admin role, not assigning admin role.

2018-09-18 17:11 UTC, CEOehis commented on server/controllers/adminHandleRoles.js
> +   * assign a user an admin role
Thanks for the resource. That was an oversight. I'll fix that ASAP.

2018-09-18 17:12 UTC, CEOehis commented on server/routes/api/admin.js
>  const adminRoutes = require('express').Router();
Thanks. I'll fix that ASAP.

2018-09-18 17:36 UTC, iamuchejude commented on server/middleware/auth.js
> +   * @param {*} req
It's advised you describe you add a description of a function parameter in jsdoc for better readability of your code.

2018-09-18 17:40 UTC, iamuchejude reviewed
It's advised you describe you add a description of a function parameter in jsdoc for better readability of your code.
Example is:
```
@params {obj} res response object
```

2018-09-18 17:40 UTC, iamuchejude approved these changes
It's advised you describe you add a description of a function parameter in jsdoc for better readability of your code. You did not do that in lines 99-101 in middleware/auth.js
An example is:
```
@params {obj} res response object
```

2018-09-19 08:34 UTC, aknwosu commented on server/middleware/auth.js
> +      const error = new Error('you are not a Super Admin');
only a Super Admin can take this action

2018-09-20 11:05 UTC, merged